# Generated by Django 3.0.6 on 2020-05-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20200513_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_img/defult.png', upload_to='post_img/'),
        ),
    ]
